// Generated by CoffeeScript 1.8.0
var Development, Packager, Production;

Development = require('./cache/development_cache');

Production = require('./cache/production_cache');

module.exports = Packager = (function() {
  function Packager() {}

  Packager.prototype.mount = function(conf) {
    var cache, env, tags;
    if (conf == null) {
      conf = {};
    }
    if (!(conf.app && typeof conf.app.get === 'function')) {
      throw 'requires conf.app as express app instance';
    }
    if (!conf.name) {
      throw 'requires conf.name as package name';
    }
    if (!conf.src) {
      throw 'requires conf.src as path to package scripts';
    }
    if (!conf.scripts) {
      throw 'requires conf.scripts as list of paths relative to conf.src';
    }
    env = process.env.NODE_ENV || process.env.ENV || 'development';
    if (env === 'production') {
      cache = new Production;
      tags = cache.route(conf);
      return tags;
    } else {
      cache = new Development;
      tags = cache.route(conf);
      return tags;
    }
  };

  return Packager;

})();
