// Generated by CoffeeScript 1.6.3
var ProductionCache, cache, fs, path;

path = require('path');

fs = require('fs');

cache = {};

module.exports = ProductionCache = (function() {
  function ProductionCache() {}

  ProductionCache.prototype.route = function(conf) {
    var app, name, route, script, scripts, src, _i, _len, _results;
    app = conf.app;
    scripts = conf.scripts;
    src = conf.src;
    name = conf.name;
    _results = [];
    for (_i = 0, _len = scripts.length; _i < _len; _i++) {
      script = scripts[_i];
      route = "/" + name + "/" + script;
      _results.push(app.get(route, function(req, res) {
        var file, match;
        res.header({
          'Content-Type': 'text/javascript'
        });
        if (cache[route] != null) {
          return res.send(cache[route]);
        }
        match = req.path.match(new RegExp("^\/" + name + "\/(.*)"));
        file = path.join(src, match[1]);
        return fs.readFile(file, function(err, data) {
          if (err == null) {
            cache[route] = data;
            return res.send(data);
          }
          res.statusCode = 404;
          return res.send();
        });
      }));
    }
    return _results;
  };

  return ProductionCache;

})();
