// Generated by CoffeeScript 1.6.3
var ProductionCache;

module.exports = ProductionCache = (function() {
  function ProductionCache() {}

  ProductionCache.prototype.route = function() {};

  return ProductionCache;

})();
